version: '3'
services:
  web:
    build: ./stable
    ports:
      - 8888:80
    links:
      - db
    volumes:
      - images:/var/www/html/images
  db:
    image: mariadb
    environment:
      # @see https://github.com/wikimedia/mediawiki/blob/master/includes/DefaultSettings.php
      MYSQL_DATABASE: 'my_wiki'
      MYSQL_USER: 'wikiuser'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
  images:
